<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Clayzor.Lib.DALC</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.*" />
    <PackageReference Include="Dapper" Version="2.*" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Clayzor.Lib.Web.Controls.Tests" />
    <InternalsVisibleTo Include="Clayzor.Lib.Entities" />
  </ItemGroup>
</Project>
